# Generated by Django 5.0.2 on 2024-08-02 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_mod_ordenes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='nombre_cliente',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='orden',
            name='numero_telefono_cliente',
            field=models.IntegerField(default=0),
        ),
    ]
