# Generated by Django 5.0.2 on 2024-08-03 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_mod_facturas', '0002_alter_factura_numero_factura'),
        ('sub_mod_ordenes', '0002_orden_nombre_cliente_orden_numero_telefono_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='factura',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sub_mod_facturas.factura'),
        ),
    ]
