# Generated by Django 5.0.2 on 2024-08-03 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_mod_ordenes', '0003_orden_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenitem',
            name='precio_unitario',
            field=models.FloatField(default=0),
        ),
    ]
