# Generated by Django 5.0.2 on 2024-08-04 01:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_mod_ordenes', '0004_ordenitem_precio_unitario'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='tiempo_despacho_esperado',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='orden',
            name='tiempo_despacho_real',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
