# Generated by Django 5.0.2 on 2024-08-08 04:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_mod_ordenes', '0005_orden_tiempo_despacho_esperado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='tiempo_despacho_esperado',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
