# Generated by Django 5.0.2 on 2024-08-08 20:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_mod_ordenes', '0006_alter_orden_tiempo_despacho_esperado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='tiempo_despacho_esperado',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
