# Generated by Django 5.0.2 on 2024-07-08 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mod_ventas', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
