# Generated by Django 5.0.2 on 2024-07-24 00:51

import django.core.validators
from django.db import migrations, models
from datetime import date

class Migration(migrations.Migration):

    dependencies = [
        ('sub_mod_productos', '0002_producto_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='precio',
        ),
        migrations.AddField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='codigo_lote',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_vencimiento',
            field=models.DateField(default=date.today),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_compra',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_venta',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
