# Generated by Django 5.0.2 on 2024-07-24 01:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_mod_productos', '0003_remove_producto_precio_producto_activo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fecha_vencimiento',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='producto',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
