# Generated by Django 5.0.2 on 2024-07-24 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_mod_productos', '0006_alter_producto_fecha_vencimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='fecha_vencimiento',
        ),
    ]
