# Generated by Django 5.0.2 on 2024-07-29 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_mod_productos', '0008_producto_fecha_vencimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descuento',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
