# Generated by Django 5.0.2 on 2024-07-29 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_mod_productos', '0010_producto_proveedor_id'),
        ('sub_mod_proveedores', '0002_remove_proveedor_descripcion_proveedor_activo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='proveedor_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sub_mod_proveedores.proveedor'),
        ),
    ]
