# Generated by Django 5.0.2 on 2024-07-29 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_mod_productos', '0012_alter_producto_proveedor_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='proveedor_id',
            new_name='proveedor',
        ),
    ]
