# Generated by Django 5.0.2 on 2024-07-29 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_mod_productos', '0015_producto_proveedor'),
        ('sub_mod_proveedores', '0002_remove_proveedor_descripcion_proveedor_activo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sub_mod_proveedores.proveedor'),
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo_producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sub_mod_productos.tipoproducto'),
        ),
    ]
