# Generated by Django 5.0.2 on 2024-07-30 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_mod_productos', '0018_remove_producto_tipo_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tipo_producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sub_mod_productos.tipoproducto'),
        ),
        migrations.AddField(
            model_name='tipoproducto',
            name='nombre',
            field=models.CharField(default='', max_length=100),
        ),
    ]
