# Generated by Django 5.0.2 on 2024-08-07 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_mod_productos', '0020_alter_producto_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='descuento',
        ),
    ]
