# Generated by Django 5.0.2 on 2024-07-29 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=100)),
                ('apellido1', models.CharField(default='', max_length=100)),
                ('apellido2', models.CharField(default='', max_length=100)),
                ('correo_electronico', models.EmailField(default='', max_length=254)),
                ('numero_telefonico', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'ordering': ['apellido1', 'apellido2', 'nombre'],
            },
        ),
    ]
