# Generated by Django 5.0.2 on 2024-07-29 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod_personas', '0002_alter_persona_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(default='', max_length=255),
        ),
    ]
