# Generated by Django 5.0.2 on 2024-08-03 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_mod_facturas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='numero_factura',
            field=models.IntegerField(unique=True),
        ),
    ]
