# Generated by Django 5.0.2 on 2024-08-08 20:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_mod_proveedores', '0003_proveedor_saldo_adeudado_pagoproveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagoproveedor',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='pagoproveedor',
            name='descripcion',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='pagoproveedor',
            name='proveedor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='sub_mod_proveedores.proveedor'),
        ),
    ]
